pipeline {
    agent any
    
    stages {
    
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh '''
                        docker rm -f nodemain || true
                        docker run -d -p 3000:3000 --name nodemain nodemain-v1.0
                    '''
                    
                }
            }
        }
    }
}
