pipeline {
    agent any
    
    stages {

        stage('Pull image') {
            steps {
                script {
                    sh 'docker pull asasai001/lab3-cicd:nodedev-v1.0'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh '''
                        docker rm -f nodedev || true
                        docker run -d -p 3001:3000 --name nodedev asasai001/lab3-cicd:nodedev-v1.0
                    '''
                    
                }
            }
        }
    }
}
